/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package facturacion;

import hibernateUtil.BussinessException;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.UIManager;

/**
 *
 * @author ANDRES
 */
public class Interfaz_principal extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_principal
     */
    public Interfaz_principal() {
        try {
//            UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
//            UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
            UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (Exception e) {
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane(){

            ImageIcon icon = new ImageIcon("../faturacion/imagenes/lab.png");
            Image image = icon.getImage();

            Image newimage = image.getScaledInstance(1200, 855, Image.SCALE_SMOOTH);

            @Override
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                g.drawImage(newimage, 0, 0, this);
            }
        };
        jScrollPane1 = new javax.swing.JScrollPane(new TreeInterfazPrincipal());
        jScrollPane2 = new javax.swing.JScrollPane();
        jButtonBuscar = new javax.swing.JButton();
        jtfBuscarPaciente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonNuevoResultado = new javax.swing.JButton();
        jMenuPrincipal = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemResultadoNuevo = new javax.swing.JMenuItem();
        jMenuItemResultadoBuscar = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemPacienteNuevo = new javax.swing.JMenuItem();
        jMenuItemPacienteBuscar = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItemPruebaNuevaArea = new javax.swing.JMenuItem();
        jMenuItemPruebaNuevaPrueba = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LabSolution");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1500, 800));

        jDesktopPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane2.setBackground(java.awt.Color.white);
        jScrollPane2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(new JTablePacientes(true));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("PRUEBAS");

        jLabel2.setText("PACIENTES");

        jButtonNuevoResultado.setText("Nuevo");
        jButtonNuevoResultado.setToolTipText("Nuevo Resultado");
        jButtonNuevoResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoResultadoActionPerformed(evt);
            }
        });
        //try{
            //Image img = ImageIO.read(getClass().getResource("../facturacion/imagenes/add.png"));
            //    jButtonNuevoResultado.setIcon(new ImageIcon(img));
            //}catch(Exception e){
            //
            //}

        jMenuPrincipal.setEnabled(false);
        jMenuPrincipal.setFocusable(false);
        jMenuPrincipal.setName(""); // NOI18N

        jMenu4.setText("Resultado");

        jMenuItemResultadoNuevo.setText("Nuevo");
        jMenuItemResultadoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemResultadoNuevoActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemResultadoNuevo);

        jMenuItemResultadoBuscar.setText("Buscar");
        jMenu4.add(jMenuItemResultadoBuscar);

        jMenuPrincipal.add(jMenu4);

        jMenu5.setText("Paciente");

        jMenuItemPacienteNuevo.setText("Nuevo");
        jMenuItemPacienteNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPacienteNuevoActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemPacienteNuevo);

        jMenuItemPacienteBuscar.setText("Buscar");
        jMenuItemPacienteBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPacienteBuscarActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemPacienteBuscar);

        jMenuPrincipal.add(jMenu5);

        jMenu6.setText("Prueba");

        jMenuItemPruebaNuevaArea.setText("Nueva Area");
        jMenuItemPruebaNuevaArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPruebaNuevaAreaActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemPruebaNuevaArea);

        jMenuItemPruebaNuevaPrueba.setText("Nueva Prueba");
        jMenuItemPruebaNuevaPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPruebaNuevaPruebaActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemPruebaNuevaPrueba);

        jMenuPrincipal.add(jMenu6);

        setJMenuBar(jMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonNuevoResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1259, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jButtonNuevoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemResultadoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemResultadoNuevoActionPerformed
        jMenuItemResultadoNuevo.setEnabled(false);
        Interfaz_Resultado res = new Interfaz_Resultado();
        jDesktopPane1.add(res);
        res.show();          // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemResultadoNuevoActionPerformed

    private void jMenuItemPacienteNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPacienteNuevoActionPerformed
        // TODO add your handling code here:}
        jMenuItemPacienteNuevo.setEnabled(false);
        jMenuItemPacienteBuscar.setEnabled(false);
        Interfaz_Pacientes cli = new Interfaz_Pacientes();
        jDesktopPane1.add(cli);
        cli.show();
    }//GEN-LAST:event_jMenuItemPacienteNuevoActionPerformed

    private void jMenuItemPacienteBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPacienteBuscarActionPerformed
        jMenuItemPacienteNuevo.setEnabled(false);
        jMenuItemPacienteBuscar.setEnabled(false);
        Interfaz_BuscarPacientes buscar = new Interfaz_BuscarPacientes();
        jDesktopPane1.add(buscar);
        buscar.show();
    }//GEN-LAST:event_jMenuItemPacienteBuscarActionPerformed

    private void jMenuItemPruebaNuevaAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPruebaNuevaAreaActionPerformed
        // TODO add your handling code here:
        jMenuItemPruebaNuevaArea.setEnabled(false);
        Interfaz_GrupoPruebas gp = new Interfaz_GrupoPruebas();
        jDesktopPane1.add(gp);
        gp.show();
    }//GEN-LAST:event_jMenuItemPruebaNuevaAreaActionPerformed

    private void jMenuItemPruebaNuevaPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPruebaNuevaPruebaActionPerformed
        jMenuItemPruebaNuevaPrueba.setEnabled(false);
        Interfaz_Prueba interfaz_Prueba = new Interfaz_Prueba();
        jDesktopPane1.add(interfaz_Prueba);
        interfaz_Prueba.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemPruebaNuevaPruebaActionPerformed

    private void jButtonNuevoResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoResultadoActionPerformed
        // TODO add your handling code here:
        jMenuItemResultadoNuevo.setEnabled(false);
        Interfaz_Resultado res = new Interfaz_Resultado();
        jDesktopPane1.add(res);
        res.show();
        jButtonNuevoResultado.setEnabled(false);
    }//GEN-LAST:event_jButtonNuevoResultadoActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButtonBuscar;
    public static javax.swing.JButton jButtonNuevoResultado;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    public static javax.swing.JMenuItem jMenuItemPacienteBuscar;
    public static javax.swing.JMenuItem jMenuItemPacienteNuevo;
    public static javax.swing.JMenuItem jMenuItemPruebaNuevaArea;
    public static javax.swing.JMenuItem jMenuItemPruebaNuevaPrueba;
    private javax.swing.JMenuItem jMenuItemResultadoBuscar;
    public static javax.swing.JMenuItem jMenuItemResultadoNuevo;
    private javax.swing.JMenuBar jMenuPrincipal;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextField jtfBuscarPaciente;
    // End of variables declaration//GEN-END:variables
}
