/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facturacion;

import dao.ReportDaoImpl;
import hibernateUtil.BussinessException;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JRViewer;

/**
 *
 * @author marcosguti
 */
public class ReportFrame extends javax.swing.JFrame {
//JFrame jInternalFrame = new JFrame();
//            Interfaz_principal.jDesktopPane1.add(jInternalFrame);
//            jInternalFrame.show();
             
    /**
     * Creates new form ReportFrame
     */
    public ReportFrame(HashMap<String, Object> reportMap) {
        initComponents();
        createReport(reportMap);
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public  void createReport(HashMap<String, Object> reportMap){
    ReportDaoImpl reporDaoImpl = new ReportDaoImpl();
        try {
            String path=getClass().getResource("../reports/LabReport.jrxml").getPath();
           JasperPrint print = reporDaoImpl.generatePdfReport(getClass().getResource("../reports/LabReport.jrxml").getPath(), reportMap); //              Interfaz_principal.jDesktopPane1.add(new JRViewer(print));
         this.getContentPane().add(new JRViewer(print));
         this.pack();
             this.setVisible(true);
            this.setSize(1000, 800);
        } catch (SQLException ex) {
            Logger.getLogger(ReportFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
               
                  
}
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
